Repository ucbrise/clipper, pull requests merged in 2018-05, with the labels that each got.

#487 Don't quit on warning when installing R dependencies
  containers/R/install_container_dependencies.R
  containers/R/tests/install_test_dependencies.R
Labels: type: maintenance

#454 Added functionality to query previous version models
  integration-tests/clipper_admin_tests.py
  src/frontends/src/query_frontend.hpp
  src/frontends/src/query_frontend_tests.cpp
  src/libclipper/src/containers.cpp
  src/libclipper/src/redis.cpp
Labels: status: accepted, type: enhancement

#489 Support Boost 1.67.0
  cmake/FindBoost.cmake
Labels: status: accepted

#481 Fix an infinite loop of GarbageCollectionThread
  src/libclipper/include/clipper/threadpool.hpp
  src/libclipper/src/containers.cpp
  src/libclipper/src/rpc_service.cpp
  src/libclipper/test/threadpool_test.cpp
Labels: status: needs review, type: bug

#497 Fix issues with model version querying
  src/frontends/src/query_frontend.hpp
Labels: type: bug

#393 Performance improvements: RPC, Data management, hashing
  CMakeLists.txt
  bin/run_unittests.sh
  cmake/Findcityhash.cmake
  containers/R/rclipper_serve/src/container_parsing.hpp
  containers/R/rclipper_serve/src/container_rpc.cpp
  containers/R/rclipper_serve/src/container_rpc.hpp
  containers/R/rclipper_serve/src/datatypes.hpp
  containers/container_implementation.md
  containers/jvm/clipper-container/src/main/java/ai/clipper/container/data/ByteVector.java
  containers/jvm/clipper-container/src/main/java/ai/clipper/container/data/DataVectorParser.java
  containers/jvm/clipper-container/src/main/java/ai/clipper/container/data/DoubleVector.java
  containers/jvm/clipper-container/src/main/java/ai/clipper/container/data/FloatVector.java
  containers/jvm/clipper-container/src/main/java/ai/clipper/container/data/IntVector.java
  containers/jvm/clipper-container/src/main/java/ai/clipper/container/data/SerializableString.java
  containers/jvm/clipper-examples/src/main/java/ai/clipper/examples/container/NoOpModel.java
  containers/jvm/clipper-examples/src/main/java/ai/clipper/examples/serve/RunContainer.java
  containers/jvm/clipper-rpc/src/main/java/ai/clipper/rpc/RPC.java
  containers/python/rpc.py
  containers/test/test_container_rpc.sh
  dockerfiles/ClipperLibBaseDockerfile
  integration-tests/clipper_admin_tests.py
  src/benchmarks/src/end_to_end_bench.cpp
  src/benchmarks/src/rpc_protocol_test.cpp
  src/benchmarks/src/rpc_service_bench.cpp
  src/container/CMakeLists.txt
  src/container/include/container/container_parsing.hpp
  src/container/include/container/container_rpc.hpp
  src/container/src/container_rpc.cpp
  src/container/src/container_tests.cpp
  src/frontends/src/query_frontend.hpp
  src/frontends/src/query_frontend_tests.cpp
  src/libclipper/CMakeLists.txt
  src/libclipper/include/clipper/datatypes.hpp
  src/libclipper/include/clipper/json_util.hpp
  src/libclipper/include/clipper/memory.hpp
  src/libclipper/include/clipper/rpc_service.hpp
  src/libclipper/include/clipper/selection_policies.hpp
  src/libclipper/include/clipper/task_executor.hpp
  src/libclipper/include/clipper/util.hpp
  src/libclipper/src/datatypes.cpp
  src/libclipper/src/json_util.cpp
  src/libclipper/src/rpc_service.cpp
  src/libclipper/src/selection_policies.cpp
  src/libclipper/src/task_executor.cpp
  src/libclipper/test/data_serialization_tests.cpp
  src/libclipper/test/json_util_test.cpp
  src/libclipper/test/metrics_test.cpp
  src/libclipper/test/rpc_service_test.cpp
  src/libclipper/test/selection_policies_test.cpp
  src/libclipper/test/task_executor_test.cpp
Labels: status: accepted, type: performance
