Repository ucbrise/clipper, pull requests merged in 2018-04, with the labels that each got.

#440 Implement Metric Server
  clipper_admin/clipper_admin/metrics/__init__.py
  clipper_admin/clipper_admin/metrics/client.py
  clipper_admin/clipper_admin/metrics/config.py
  clipper_admin/clipper_admin/metrics/schema.py
  clipper_admin/clipper_admin/metrics/server.py
  clipper_admin/requirements.txt
  clipper_admin/setup.py
  containers/python/rpc.py
  containers/python/rpc_test_container.py
  containers/test/test_container_rpc.sh
  dockerfiles/ClipperDevDockerfile
  dockerfiles/Py2RPCDockerfile
  examples/user_defined_metric/Clipper_Dashboard.json
  examples/user_defined_metric/README.md
  examples/user_defined_metric/email_msg.pickle
  examples/user_defined_metric/init_grafana.py
  examples/user_defined_metric/logistic_regressor.pickle
  examples/user_defined_metric/query.py
  examples/user_defined_metric/vectorizer.pickle
Labels: status: needs review, type: enhancement

#458 Fix QueryFrontend bug
  src/frontends/src/query_frontend.hpp
Labels: status: accepted

#457 Add functionality to delete applications
  clipper_admin/clipper_admin/clipper_admin.py
  containers/jvm/clipper-container/src/main/java/ai/clipper/container/data/ByteVector.java
  containers/jvm/clipper-container/src/main/java/ai/clipper/container/data/DoubleVector.java
  containers/jvm/clipper-container/src/main/java/ai/clipper/container/data/FloatVector.java
  containers/jvm/clipper-container/src/main/java/ai/clipper/container/data/IntVector.java
  containers/jvm/clipper-container/src/main/java/ai/clipper/container/data/SerializableString.java
  integration-tests/clipper_admin_tests.py
  src/benchmarks/src/bench_utils.hpp
  src/benchmarks/src/rpc_service_bench.cpp
  src/container/include/container/container_rpc.hpp
  src/frontends/src/query_frontend.hpp
  src/frontends/src/query_frontend_tests.cpp
  src/libclipper/include/clipper/redis.hpp
  src/libclipper/include/clipper/task_executor.hpp
  src/libclipper/src/query_processor.cpp
  src/libclipper/src/redis.cpp
  src/libs/httpserver/server_http.hpp
  src/management/src/management_frontend.hpp
  src/management/src/management_frontend_tests.cpp
Labels: status: needs revision

#444 R model serialization fixes
  containers/R/rclipper_user/DESCRIPTION
  containers/R/rclipper_user/R/serialize_model.R
  containers/R/rclipper_user/vignettes/Rclipper.Rmd
  containers/R/tests/install_test_dependencies.R
  containers/R/tests/run_tests.sh
  containers/R/tests/test_multidependency_serialization.R
  dockerfiles/ClipperDevDockerfile
Labels: status: accepted, type: bug

#470 Address k8s del_svc api change
  clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
  clipper_admin/requirements.txt
  clipper_admin/setup.py
  dockerfiles/ClipperDevDockerfile
Labels: status: needs review

#378 Container heartbeat
  integration-tests/clipper_admin_tests.py
  src/benchmarks/src/rpc_protocol_test.cpp
  src/benchmarks/src/rpc_service_bench.cpp
  src/libclipper/include/clipper/containers.hpp
  src/libclipper/include/clipper/exceptions.hpp
  src/libclipper/include/clipper/rpc_service.hpp
  src/libclipper/include/clipper/task_executor.hpp
  src/libclipper/include/clipper/threadpool.hpp
  src/libclipper/src/containers.cpp
  src/libclipper/src/exceptions.cpp
  src/libclipper/src/rpc_service.cpp
  src/libclipper/test/task_executor_test.cpp
  src/libclipper/test/threadpool_test.cpp
Labels: status: accepted, type: enhancement

#480 Shorten input for kube integration test
  integration-tests/clipper_metric_kube.py
  integration-tests/kubernetes_integration_test.py
Labels: status: accepted
