Repository ucbrise/clipper, pull requests merged in 2018-02, with the labels that each got.

#410 Explicitly install redis-server when building test container
  dockerfiles/ClipperTestsDockerfile
Labels: status: accepted, type: bug

#405 Added MXNet Deployment Capability (replaces #390)
  bench/bench_init.py
  bin/build_docker_images.sh
  clipper_admin/clipper_admin/deployers/mxnet.py
  containers/python/mxnet_container.py
  containers/python/mxnet_container_entry.sh
  dockerfiles/ClipperTestsDockerfile
  dockerfiles/MXNetContainerDockerfile
  integration-tests/deploy_mxnet_models.py
Labels: status: needs review, type: enhancement

#413 [Metric] Refactor Frontend-exporter
  clipper_admin/clipper_admin/docker/docker_metric_utils.py
  monitoring/front_end_exporter.py
Labels: status: needs review, type: maintenance

#414 :memo: Improved README with direct links to github profiles
  README.md
Labels: status: accepted, type: documentation

#415 Fix a bug that QueryFrontend adds a garbage to http response
  src/frontends/src/query_frontend.hpp
Labels: type: bug, type: maintenance

#362 PyTorch + ONNX + Caffe2 Model deployer
  bin/build_docker_images.sh
  clipper_admin/clipper_admin/deployers/onnx.py
  containers/python/caffe2_onnx_container.py
  containers/python/caffe2_onnx_container_entry.sh
  dockerfiles/Caffe2OnnxDockerfile
  integration-tests/deploy_pytorch_to_caffe2_with_onnx.py
Labels: status: needs revision, type: enhancement
