Repository ucbrise/clipper, pull requests merged in 2018-03, with the labels that each got.

#418 results of profiling JSON parsing latency
  src/frontends/README.md
  src/frontends/graphs/graph1.png
  src/frontends/graphs/graph2.png
  src/frontends/graphs/graph3.png
Labels: status: needs review

#426 Fix installation order errors in deployer containers
  dockerfiles/Caffe2OnnxDockerfile
  dockerfiles/MXNetContainerDockerfile
  dockerfiles/PySparkContainerDockerfile
  dockerfiles/PyTorchContainerDockerfile
  dockerfiles/TensorFlowDockerfile
Labels: status: accepted, type: bug

#432 fix libsodium build issue
  dockerfiles/ClipperTestsDockerfile
Labels: status: needs review, type: bug

#429 [Metrics] Frontend-exporter fault tolerance quick fix
  monitoring/front_end_exporter.py
Labels: status: needs review

#438 Upgrade SimpleWebServer to version 2.1.1
  src/frontends/src/query_frontend.hpp
  src/frontends/src/query_frontend_main.cpp
  src/frontends/src/query_frontend_tests.cpp
  src/libs/httpserver/server_http.hpp
  src/management/src/management_frontend.hpp
  src/management/src/management_frontend_main.cpp
  src/management/src/management_frontend_tests.cpp
Labels: status: accepted

#427 [Metrics] Kubernetes Support & Maintenance
  bin/run_unittests.sh
  clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
  clipper_admin/clipper_admin/kubernetes/kubernetes_metric_utils.py
  clipper_admin/clipper_admin/kubernetes/prom_configmap.yaml
  clipper_admin/clipper_admin/kubernetes/prom_deployment.yaml
  clipper_admin/clipper_admin/kubernetes/prom_service.yaml
  clipper_admin/clipper_admin/kubernetes/query-frontend-deployment.yaml
  examples/monitoring/README.md
  integration-tests/clipper_metric_docker.py
  integration-tests/clipper_metric_kube.py
  monitoring/README.md
Labels: status: accepted

#431 Add ability to install packages + xgboost model deployer + example
  clipper_admin/clipper_admin/clipper_admin.py
  clipper_admin/clipper_admin/deployers/mxnet.py
  clipper_admin/clipper_admin/deployers/onnx.py
  clipper_admin/clipper_admin/deployers/pyspark.py
  clipper_admin/clipper_admin/deployers/python.py
  clipper_admin/clipper_admin/deployers/pytorch.py
  clipper_admin/clipper_admin/deployers/tensorflow.py
  integration-tests/deploy_xgboost_models.py
Labels: status: accepted, type: enhancement
