Repository ucbrise/clipper, pull requests merged in 2019-05, with the labels that each got.

#685 [CI] Try to stabilize Travis job
  .travis.yml
  bin/run_travis.sh
Labels: status: needs review, type: maintenance

#689 Fix a bug that a new model replica couldn't be registerd with the Clipper's RPCService
  src/libclipper/include/clipper/rpc_service.hpp
  src/libclipper/src/rpc_service.cpp
Labels: status: needs review, type: bug

#690 [CI] Randomize RPCService's port and handle NoSuchProcess error properly
  clipper_admin/clipper_admin/metrics/server.py
  containers/test/test_container_rpc.sh
Labels: status: needs review, type: maintenance

#653 Rename 'delete_application' to 'unregister_application' in clipper_admin
  clipper_admin/clipper_admin/clipper_admin.py
  integration-tests/clipper_admin_tests.py
Labels: status: needs review, type: enhancement

#675 Updagrade the version of mxnet to 1.4.* for mxnetcontainerdockerfile.
  dockerfiles/ClipperDevDockerfile
  dockerfiles/ClipperPy35DevDockerfile
  dockerfiles/MXNetContainerDockerfile
  integration-tests/clipper_metric_docker.py
  integration-tests/deploy_mxnet_models.py
  integration-tests/test_utils.py
Labels: status: needs revision, type: bug

#693 #692: Added get_metric_addr to the ClipperConnection
  clipper_admin/clipper_admin/clipper_admin.py
Labels: type: enhancement

#691 Update SimpleWebServer to the latest version(29 Apr, 2019 - d6985ed6)
  src/libs/httpserver/server_http.hpp
  src/libs/httpserver/status_code.hpp
  src/libs/httpserver/utility.hpp
Labels: status: in progress, type: enhancement

#667 Change k8s ServiceTypes to be changeable
  clipper_admin/clipper_admin/container_manager.py
  clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
  clipper_admin/clipper_admin/kubernetes/mgmt-frontend-service.yaml
  clipper_admin/clipper_admin/kubernetes/prom_service.yaml
  clipper_admin/clipper_admin/kubernetes/query-frontend-rpc-service.yaml
  clipper_admin/clipper_admin/kubernetes/query-frontend-service.yaml
  clipper_admin/clipper_admin/kubernetes/redis-service.yaml
  integration-tests/kubernetes_integration_test.py
  integration-tests/test_utils.py
Labels: status: needs review, type: enhancement

#697 get_metric_addr(): Added a return statement
  clipper_admin/clipper_admin/clipper_admin.py
Labels: status: accepted, type: bug

#699 [CI] Recover CI job failures
  bin/retry_with_timeout.py
  bin/run_ci.sh
  bin/run_unittests.sh
  bin/shipyard/clipper_test.cfg.py
  clipper_admin/clipper_admin/docker/docker_container_manager.py
  clipper_admin/clipper_admin/docker/docker_metric_utils.py
  clipper_admin/clipper_admin/kubernetes/kubernetes_metric_utils.py
  containers/python/rpc.py
  dockerfiles/ClipperDevDockerfile
  dockerfiles/ClipperPy35DevDockerfile
  dockerfiles/FrontendExporterDockerfile
  dockerfiles/Py2RPCDockerfile
  dockerfiles/Py35RPCDockerfile
  dockerfiles/Py36RPCDockerfile
  integration-tests/clipper_admin_tests.py
  integration-tests/clipper_metric_docker.py
  integration-tests/test_utils.py
  src/frontends/src/query_frontend_tests.cpp
Labels: status: needs review, type: maintenance

#700 Print necessary stackstace information when crashed
  containers/mgmt_frontend/mgmt_frontend_entry.sh
  containers/query_frontend/query_frontend_entry.sh
  dockerfiles/ManagementFrontendDockerfile
  dockerfiles/QueryFrontendDockerfile
  src/frontends/src/query_frontend_main.cpp
  src/management/src/management_frontend_main.cpp
Labels: status: needs review, type: maintenance

#707 [CI] Fix maintenance scripts
  bin/cleanup_jenkins.sh
  bin/retry_with_timeout.py
  bin/run_ci.sh
Labels: status: needs review, type: maintenance

#594 Keras deployer
  .gitignore
  bin/shipyard/clipper_docker.cfg.py
  bin/shipyard/clipper_test.cfg.py
  clipper_admin/clipper_admin/deployers/keras.py
  containers/python/keras_container.py
  dockerfiles/ClipperDevDockerfile
  dockerfiles/ClipperPy35DevDockerfile
  dockerfiles/KerasContainerDockerfile
  integration-tests/deploy_keras_models.py
Labels: status: needs revision, type: enhancement

#602 Implement delete_versioned_model API
  clipper_admin/clipper_admin/clipper_admin.py
  integration-tests/clipper_admin_tests.py
  src/libclipper/include/clipper/redis.hpp
  src/libclipper/include/clipper/task_executor.hpp
  src/libclipper/include/clipper/threadpool.hpp
  src/libclipper/src/containers.cpp
  src/libclipper/src/redis.cpp
  src/libclipper/test/redis_test.cpp
  src/management/src/management_frontend.hpp
  src/management/src/management_frontend_tests.cpp
Labels: status: needs review, type: enhancement

#711 Clean up the versioned model's batch_size and metrics when deleting it
  src/libclipper/include/clipper/containers.hpp
  src/libclipper/include/clipper/metrics.hpp
  src/libclipper/include/clipper/task_executor.hpp
  src/libclipper/src/containers.cpp
  src/libclipper/src/metrics.cpp
Labels: status: needs review, type: bug

#694 Adding RBAC support in kubernetes config (V2)
  bin/run_travis.sh
  clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
  clipper_admin/clipper_admin/kubernetes/rbac_cluster_role.yaml
  clipper_admin/clipper_admin/kubernetes/rbac_cluster_role_binding.yaml
Labels: status: in progress, type: enhancement
