Repository ucbrise/clipper, pull requests merged in 2019-06, with the labels that each got.

#714 Update the version of base libraries and OS
  cmake/FindBoost.cmake
  cmake/FindPackageHandleStandardArgs.cmake
  cmake/FindPackageMessage.cmake
  dockerfiles/ClipperDevDockerfile
  dockerfiles/ClipperLibBaseDockerfile
  dockerfiles/ClipperPy35DevDockerfile
  src/benchmarks/src/end_to_end_bench.cpp
  src/frontends/src/query_frontend.hpp
  src/libclipper/src/query_processor.cpp
  src/libclipper/test/task_executor_test.cpp
Labels: status: needs review, type: maintenance

#717 Enable TCP keep alive for redox
  dockerfiles/ClipperPy35TestsDockerfile
  dockerfiles/ClipperTestsDockerfile
  dockerfiles/ManagementFrontendDockerfile
  dockerfiles/QueryFrontendDockerfile
  src/libs/patches/redis_keepalive.patch
Labels: status: needs review, type: bug

#719 Add check for external redis ip address to prevent KeyError (#571)
  clipper_admin/clipper_admin/docker/docker_container_manager.py
Labels: status: needs review, type: bug

#720 Upgrade Tensorflow version(1.6 -> 1.13)
  dockerfiles/ClipperDevDockerfile
  dockerfiles/ClipperPy35DevDockerfile
  dockerfiles/KerasContainerDockerfile
  dockerfiles/TensorFlowDockerfile
Labels: status: accepted, type: maintenance

#721 Handle trailing slash on predict url
  integration-tests/clipper_admin_tests.py
  src/frontends/src/query_frontend.hpp
Labels: status: needs review, type: bug

#726 Upgrade torch(1.0.* -> 1.1.*) and torchvision(0.2.* -> 0.3.*)
  dockerfiles/ClipperDevDockerfile
  dockerfiles/ClipperPy35DevDockerfile
  dockerfiles/PyTorchContainerDockerfile
Labels: status: in progress, type: maintenance

#731 [CI] Cleanup Docker for CI Build
  bin/cleanup_jenkins.sh
  bin/run_ci.sh
Labels: status: in progress, type: maintenance

#728 Implement docker_api_utils for DockerContainerManager
  clipper_admin/clipper_admin/docker/docker_api_utils.py
  clipper_admin/clipper_admin/docker/docker_container_manager.py
  clipper_admin/clipper_admin/docker/docker_metric_utils.py
  integration-tests/deploy_keras_models.py
Labels: status: needs review, type: maintenance

#712 Adding ready to run Jupyter notebooks for various ML frameworks
  examples/frameworks/diabetes.txt
  examples/frameworks/keras_on_docker_example.ipynb
  examples/frameworks/mxnet_on_docker_example.ipynb
  examples/frameworks/pyspark_on_docker_example.ipynb
  examples/frameworks/pytorch_on_docker_example.ipynb
  examples/frameworks/scikit_on_docker_example.ipynb
  examples/frameworks/tensorflow_on_docker_example.ipynb
  examples/frameworks/xgboost_on_docker_example.ipynb
  examples/image_query/keras_on_docker_example.ipynb
  examples/image_query/pytorch_on_docker_example.ipynb
Labels: type: documentation

#732 Fixing the `stop_models` functions by calling explicitly the removal of the replica sets and pods
  clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py
Labels: status: accepted, type: bug
